# Generated by Django 5.2.13 on 2026-04-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='course',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
