# Generated by Django 5.2.13 on 2026-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_download_count_alter_material_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
