# Generated by Django 5.2.13 on 2026-04-22 02:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='download_count',
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
